<?xml version="1.0" encoding="Shift_JIS"?>
<?xml-stylesheet type="text/xsl" href="hoot.xsl"?>
<!DOCTYPE gamelist [
	<!ELEMENT gamelist (game|bind|childlists)*>
	<!ATTLIST gamelist date CDATA #IMPLIED>
	<!ELEMENT childlists (list)*>
	<!ELEMENT list (#PCDATA)>
	<!ELEMENT bind (exts,driver,options?)>
	<!ELEMENT exts (ext)*>
	<!ELEMENT ext (#PCDATA)>
	<!ELEMENT game (name,driver,driveralias?,options?,romlist?,titlelist?)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT driver (#PCDATA)>
	<!ATTLIST driver type CDATA #IMPLIED>
	<!ELEMENT driveralias (#PCDATA)>
	<!ATTLIST driveralias type CDATA #IMPLIED>
	<!ELEMENT options (option)*>
	<!ELEMENT option EMPTY>
	<!ATTLIST option name CDATA #REQUIRED
		 value CDATA #REQUIRED>
	<!ELEMENT romlist (rom)*>
	<!ATTLIST romlist archive CDATA #IMPLIED>
	<!ELEMENT rom (#PCDATA)>
	<!ATTLIST rom type CDATA #REQUIRED
		offset CDATA #IMPLIED>
	<!ELEMENT titlelist (title|range)*>
	<!ELEMENT title (#PCDATA)>
	<!ATTLIST title code CDATA #REQUIRED
					type CDATA #IMPLIED>
	<!ELEMENT range (#PCDATA)>
	<!ATTLIST range min CDATA #REQUIRED
					max CDATA #REQUIRED
					extcode CDATA #IMPLIED>
]>
<gamelist date="2005/09/25">
<game>
<name>[SNES] Kamaitachi no Yoru / Kojiro Nakashima, Kota Kato / 1994 Chunsoft</name>
<driver type="spc">snes</driver>
<driveralias type="SNES">chunsoft</driveralias>
<options>
<option name="apu_mix" value="0x200"/>
</options>
<romlist archive="kny">
<rom type="data" offset="0x01">kny-01.spc</rom>
<rom type="data" offset="0x02">kny-02.spc</rom>
<rom type="data" offset="0x03">kny-03.spc</rom>
<rom type="data" offset="0x04">kny-04.spc</rom>
<rom type="data" offset="0x05">kny-05.spc</rom>
<rom type="data" offset="0x06">kny-06.spc</rom>
<rom type="data" offset="0x07">kny-07.spc</rom>
<rom type="data" offset="0x08">kny-08.spc</rom>
<rom type="data" offset="0x09">kny-09.spc</rom>
<rom type="data" offset="0x0a">kny-10.spc</rom>
<rom type="data" offset="0x0b">kny-11.spc</rom>
<rom type="data" offset="0x0c">kny-12.spc</rom>
<rom type="data" offset="0x0d">kny-13.spc</rom>
<rom type="data" offset="0x0e">kny-14.spc</rom>
<rom type="data" offset="0x0f">kny-15.spc</rom>
<rom type="data" offset="0x10">kny-16.spc</rom>
<rom type="data" offset="0x11">kny-17.spc</rom>
<rom type="data" offset="0x12">kny-18.spc</rom>
<rom type="data" offset="0x13">kny-19.spc</rom>
<rom type="data" offset="0x14">kny-20.spc</rom>
<rom type="data" offset="0x15">kny-21.spc</rom>
<rom type="data" offset="0x16">kny-22.spc</rom>
<rom type="data" offset="0x17">kny-23.spc</rom>
<rom type="data" offset="0x18">kny-24.spc</rom>
<rom type="data" offset="0x19">kny-25.spc</rom>
<rom type="data" offset="0x1a">kny-26.spc</rom>
<rom type="data" offset="0x1b">kny-27.spc</rom>
<rom type="data" offset="0x1c">kny-28.spc</rom>
<rom type="data" offset="0x1d">kny-29.spc</rom>
<rom type="data" offset="0x1e">kny-30.spc</rom>
<rom type="data" offset="0x1f">kny-31.spc</rom>
<rom type="data" offset="0x20">kny-32.spc</rom>
<rom type="data" offset="0x21">kny-33.spc</rom>
<rom type="data" offset="0x22">kny-34.spc</rom>
<rom type="data" offset="0x23">kny-35.spc</rom>
<rom type="data" offset="0x24">kny-36.spc</rom>
<rom type="data" offset="0x25">kny-37.spc</rom>
<rom type="data" offset="0x26">kny-38.spc</rom>
<rom type="data" offset="0x27">kny-b01.spc</rom>
<rom type="data" offset="0x28">kny-b02.spc</rom>
<rom type="data" offset="0x29">kny-b03.spc</rom>
<rom type="data" offset="0x2a">kny-b04.spc</rom>
<rom type="data" offset="0x2b">kny-b05.spc</rom>
<rom type="data" offset="0x2c">kny-b06.spc</rom>
<rom type="data" offset="0x2d">kny-b07.spc</rom>
<rom type="data" offset="0x2e">kny-b08.spc</rom>
<rom type="data" offset="0x2f">kny-b09.spc</rom>
<rom type="data" offset="0x30">kny-fx01.spc</rom>
<rom type="data" offset="0x31">kny-fx02.spc</rom>
<rom type="data" offset="0x32">kny-fx03.spc</rom>
<rom type="data" offset="0x33">kny-fx04.spc</rom>
<rom type="data" offset="0x34">kny-fx05.spc</rom>
<rom type="data" offset="0x35">kny-fx06.spc</rom>
<rom type="data" offset="0x36">kny-fx07.spc</rom>
<rom type="data" offset="0x37">kny-s01.spc</rom>
<rom type="data" offset="0x38">kny-s02.spc</rom>
<rom type="data" offset="0x39">kny-s03.spc</rom>
<rom type="data" offset="0x3a">kny-s04.spc</rom>
<rom type="data" offset="0x3b">kny-s05.spc</rom>
<rom type="data" offset="0x3c">kny-s06.spc</rom>
<rom type="data" offset="0x3d">kny-s07.spc</rom>
<rom type="data" offset="0x3e">kny-s08.spc</rom>
<rom type="data" offset="0x3f">kny-s09.spc</rom>
<rom type="data" offset="0x40">kny-s10.spc</rom>
</romlist>
<titlelist>
<title code="0x01">Kamaitachi no Yoru</title>
<title code="0x02">Introduction</title>
<title code="0x03">Lovers on Ski Run</title>
<title code="0x04">Three Florescent Working Girls</title>
<title code="0x05">I'm Kayama! ~ Manlike Life</title>
<title code="0x06">Pension ~ Traces of Skies</title>
<title code="0x07">Nuisance</title>
<title code="0x08">A Late Guest</title>
<title code="0x09">Nightmare</title>
<title code="0x0a">Wandering Murderer</title>
<title code="0x0b">Strange Scene</title>
<title code="0x0c">Fondly Remembered Scenery</title>
<title code="0x0d">Doubts Beget Doubts</title>
<title code="0x0e">Single Inference</title>
<title code="0x0f">Requiem</title>
<title code="0x10">Toshio's Fury</title>
<title code="0x11">Battle</title>
<title code="0x12">Resolution</title>
<title code="0x13">Chaos</title>
<title code="0x14">Beginning of a Long Night</title>
<title code="0x15">Imminent Fear</title>
<title code="0x16">Unexpected End</title>
<title code="0x17">Devilish Homicide</title>
<title code="0x18">Illusion of a Distant Day</title>
<title code="0x19">Amber Crescent Moon</title>
<title code="0x1a">French Information Bureau SDECE</title>
<title code="0x1b">Legendary Spy</title>
<title code="0x1c">Mission</title>
<title code="0x1d">Pursuit</title>
<title code="0x1e">Something Lost...</title>
<title code="0x1f">Tracing through Snow</title>
<title code="0x20">Lover</title>
<title code="0x21">Nostalgia</title>
<title code="0x22">Recollection</title>
<title code="0x23">Evil Spirit</title>
<title code="0x24">Comedy of O</title>
<title code="0x25">Message Written in Blood</title>
<title code="0x26">Nice Treasure</title>
<title code="0x27">Unknown Song 1</title>
<title code="0x28">Unknown Song 2</title>
<title code="0x29">Unknown Song 3</title>
<title code="0x2a">Unknown Song 4</title>
<title code="0x2b">Unknown Song 5</title>
<title code="0x2c">Unknown Song 6</title>
<title code="0x2d">Unknown Song 7</title>
<title code="0x2e">Unknown Song 8</title>
<title code="0x2f">Unknown Song 9</title>
<title code="0x30">SFX 1</title>
<title code="0x31">SFX 2</title>
<title code="0x32">SFX 3</title>
<title code="0x33">SFX 4</title>
<title code="0x34">SFX 5</title>
<title code="0x35">SFX 6</title>
<title code="0x36">SFX 7</title>
<title code="0x37">Jingle 1</title>
<title code="0x38">Jingle 2</title>
<title code="0x39">Jingle 3</title>
<title code="0x3a">Jingle 4</title>
<title code="0x3b">Jingle 5</title>
<title code="0x3c">Jingle 6</title>
<title code="0x3d">Jingle 7</title>
<title code="0x3e">Jingle 8</title>
<title code="0x3f">Jingle 9</title>
<title code="0x40">Jingle 10</title>
</titlelist>
</game>

</gamelist>
