<?xml version="1.0" encoding="Shift_JIS"?>
<?xml-stylesheet type="text/xsl" href="hoot.xsl"?>
<!DOCTYPE gamelist [
	<!ELEMENT gamelist (game|bind|childlists)*>
	<!ATTLIST gamelist date CDATA #IMPLIED>
	<!ELEMENT childlists (list)*>
	<!ELEMENT list (#PCDATA)>
	<!ELEMENT bind (exts,driver,options?)>
	<!ELEMENT exts (ext)*>
	<!ELEMENT ext (#PCDATA)>
	<!ELEMENT game (name,driver,driveralias?,options?,romlist?,titlelist?)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT driver (#PCDATA)>
	<!ATTLIST driver type CDATA #IMPLIED>
	<!ELEMENT driveralias (#PCDATA)>
	<!ATTLIST driveralias type CDATA #IMPLIED>
	<!ELEMENT options (option)*>
	<!ELEMENT option EMPTY>
	<!ATTLIST option name CDATA #REQUIRED
		 value CDATA #REQUIRED>
	<!ELEMENT romlist (rom)*>
	<!ATTLIST romlist archive CDATA #IMPLIED>
	<!ELEMENT rom (#PCDATA)>
	<!ATTLIST rom type CDATA #REQUIRED
		offset CDATA #IMPLIED>
	<!ELEMENT titlelist (title|range)*>
	<!ELEMENT title (#PCDATA)>
	<!ATTLIST title code CDATA #REQUIRED
					type CDATA #IMPLIED>
	<!ELEMENT range (#PCDATA)>
	<!ATTLIST range min CDATA #REQUIRED
					max CDATA #REQUIRED
					extcode CDATA #IMPLIED>
]>
<gamelist date="2005/09/25">
	<!-- //dez -->
	<game>
		<name>[PC-98] La Blue Girl -School of Lust- (à˙èbäwâÄ LaÅôBlueGirl)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-98">dezcrima</driveralias>
		<options>
			<option name="ssg_mix" value="-16"/>
		</options>
		<romlist archive="inju_98">
			<rom type="file" offset="-1">usd_98.com</rom>
			<rom type="file" offset="-1">INJU.OV1</rom>
			<rom type="conin" offset="5">INJU.OV1</rom>
			<rom type="file" offset="0x11">INJ01.USO</rom>
			<rom type="file" offset="0x12">INJ02.USO</rom>
			<rom type="file" offset="0x13">INJ03.USO</rom>
			<rom type="file" offset="0x14">INJ04.USO</rom>
			<rom type="file" offset="0x15">INJ05.USO</rom>
			<rom type="file" offset="0x16">INJ06.USO</rom>
			<rom type="file" offset="0x17">INJ07.USO</rom>
			<rom type="file" offset="0x18">INJ08.USO</rom>
			<rom type="file" offset="0x19">INJ09.USO</rom>
			<rom type="file" offset="0x1a">INJ10.USO</rom>
			<rom type="shell" offset="0">usd_98</rom>
		</romlist>
		<titlelist>
			<title code="0x11">INJ01.USO</title>
			<title code="0x12">INJ02.USO</title>
			<title code="0x13">INJ03.USO</title>
			<title code="0x14">INJ04.USO</title>
			<title code="0x15">INJ05.USO</title>
			<title code="0x16">INJ06.USO</title>
			<title code="0x17">INJ07.USO</title>
			<title code="0x18">INJ08.USO</title>
			<title code="0x19">INJ09.USO</title>
			<title code="0x1a">INJ10.USO</title>
		</titlelist>
	</game>
	<game>
		<name>[PC-98] Youjyuu Kyoushitsu (ódèbã≥é∫)</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-98">dezcrima</driveralias>
		<options>
			<option name="ssg_mix" value="-16"/>
		</options>
		<romlist archive="youju_98">
			<rom type="file" offset="-1">usd_98.com</rom>
			<rom type="file" offset="-1">YOJU.OV1</rom>
			<rom type="conin" offset="5">YOJU.OV1</rom>
			<rom type="file" offset="0x11">YOJ_01.USO</rom>
			<rom type="file" offset="0x12">YOJ_02.USO</rom>
			<rom type="file" offset="0x13">YOJ_03.USO</rom>
			<rom type="file" offset="0x14">YOJ_04.USO</rom>
			<rom type="file" offset="0x15">YOJ_05.USO</rom>
			<rom type="file" offset="0x16">YOJ_06.USO</rom>
			<rom type="file" offset="0x17">YOJ_07.USO</rom>
			<rom type="file" offset="0x18">YOJ_08.USO</rom>
			<rom type="file" offset="0x19">YOJ_09.USO</rom>
			<rom type="file" offset="0x1a">YOJ_10.USO</rom>
			<rom type="shell" offset="0">usd_98</rom>
		</romlist>
		<titlelist>
			<title code="0x11">YOJ_01.USO</title>
			<title code="0x12">YOJ_02.USO</title>
			<title code="0x13">YOJ_03.USO</title>
			<title code="0x14">YOJ_04.USO</title>
			<title code="0x15">YOJ_05.USO</title>
			<title code="0x16">YOJ_06.USO</title>
			<title code="0x17">YOJ_07.USO</title>
			<title code="0x18">YOJ_08.USO</title>
			<title code="0x19">YOJ_09.USO</title>
			<title code="0x1a">YOJ_10.USO</title>
		</titlelist>
	</game>
</gamelist>
