<?xml version="1.0" encoding="Shift_JIS"?>
<?xml-stylesheet type="text/xsl" href="hoot.xsl"?>
<!DOCTYPE gamelist [
	<!ELEMENT gamelist (game|bind|childlists)*>
	<!ATTLIST gamelist date CDATA #IMPLIED>
	<!ELEMENT childlists (list)*>
	<!ELEMENT list (#PCDATA)>
	<!ELEMENT bind (exts,driver,options?)>
	<!ELEMENT exts (ext)*>
	<!ELEMENT ext (#PCDATA)>
	<!ELEMENT game (name,driver,driveralias?,options?,romlist?,titlelist?)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT driver (#PCDATA)>
	<!ATTLIST driver type CDATA #IMPLIED>
	<!ELEMENT driveralias (#PCDATA)>
	<!ATTLIST driveralias type CDATA #IMPLIED>
	<!ELEMENT options (option)*>
	<!ELEMENT option EMPTY>
	<!ATTLIST option name CDATA #REQUIRED
		 value CDATA #REQUIRED>
	<!ELEMENT romlist (rom)*>
	<!ATTLIST romlist archive CDATA #IMPLIED>
	<!ELEMENT rom (#PCDATA)>
	<!ATTLIST rom type CDATA #REQUIRED
		offset CDATA #IMPLIED>
	<!ELEMENT titlelist (title|range)*>
	<!ELEMENT title (#PCDATA)>
	<!ATTLIST title code CDATA #REQUIRED
					type CDATA #IMPLIED>
	<!ELEMENT range (#PCDATA)>
	<!ATTLIST range min CDATA #REQUIRED
					max CDATA #REQUIRED
					extcode CDATA #IMPLIED>
]>
<gamelist date="2005/09/25">
	<!-- //cuisse -->
	<game>
		<name>[PC-98] More and More (‚à‚ ‚ ‚ñ‚Ç‚à‚ )</name>
		<driver type="opn">pc98dos</driver>
		<driveralias type="PC-98">cuisse</driveralias>
		<options>
			<option name="fm_mix"   value="0"/>
			<option name="ssg_mix"  value="-18"/>
		</options>
		<romlist archive="mandm_98">
			<rom type="file" offset="-1">FMPP.COM</rom>
			<rom type="file" offset="-1">FMP.COM</rom>
			<rom type="file" offset="0x10">MORE_01.OPI</rom>
			<rom type="file" offset="0x11">MORE_02.OPI</rom>
			<rom type="file" offset="0x12">MORE_03.OPI</rom>
			<rom type="file" offset="0x13">MORE_04.OPI</rom>
			<rom type="file" offset="0x14">MORE_05.OPI</rom>
			<rom type="file" offset="0x15">MORE_06.OPI</rom>
			<rom type="file" offset="0x16">MORE_07.OPI</rom>
			<rom type="file" offset="0x17">MORE_08.OPI</rom>
			<rom type="file" offset="0x18">MORE_09.OPI</rom>
			<rom type="file" offset="0x19">MORE_10.OPI</rom>
			<rom type="shell" offset="0">FMP S /#12 /S</rom>
			<rom type="shell" offset="0">FMPP</rom>
		</romlist>
		<titlelist>
			<title code="0x10">MORE_01.OPI</title>
			<title code="0x11">MORE_02.OPI</title>
			<title code="0x12">MORE_03.OPI</title>
			<title code="0x13">MORE_04.OPI</title>
			<title code="0x14">MORE_05.OPI</title>
			<title code="0x15">MORE_06.OPI</title>
			<title code="0x16">MORE_07.OPI</title>
			<title code="0x17">MORE_08.OPI</title>
			<title code="0x18">MORE_09.OPI</title>
			<title code="0x19">MORE_10.OPI</title>
		</titlelist>
	</game>
</gamelist>
